# Generated by Django 4.1.6 on 2023-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название признака')),
                ('quest', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('typ', models.IntegerField(choices=[(0, 'Тип Да/Нет'), (1, 'Тип число')], unique=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Признак',
                'verbose_name_plural': 'Признаки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название направления')),
                ('code', models.CharField(max_length=10, verbose_name='Код направления')),
                ('url', models.URLField(verbose_name='Адрес сайта')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Институт')),
                ('short_name', models.CharField(max_length=10)),
                ('url', models.URLField(verbose_name='Адрес сайта')),
                ('properties', models.ManyToManyField(to='main.property')),
                ('specialities', models.ManyToManyField(to='main.specialty')),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
                'ordering': ['short_name'],
            },
        ),
    ]
